---
# tasks file for virtualbox - Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Add gpg signing key for {{ virtualbox_app_name }}
  ansible.builtin.apt_key:
    url: "{{ virtualbox_gpg_key }}"
    state: present

- name: Debian/Ubuntu Family | Adding repository {{ virtualbox_repo_debian }}
  ansible.builtin.apt_repository:
    repo: "{{ virtualbox_repo_debian }}"
    state: "{{ virtualbox_repo_desired_state }}"
    filename: "{{ virtualbox_repo_debian_filename }}"
    update_cache: yes

- name: Debian/Ubuntu Family | Installing {{ virtualbox_app_name }}-{{ virtualbox_version }}
  ansible.builtin.apt:
    name: "{{ virtualbox_app_name }}-{{ virtualbox_version }}"
    state: "{{ virtualbox_desired_state }}"
    force_apt_get: yes
    update_cache: yes
